"""create initial schema

Revision ID: 2630b41e0575
Revises:
Create Date: 2026-07-29 15:06:03.563437
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "2630b41e0575"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building",
        sa.Column("building_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("building_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("building_id", name=op.f("pk_building")),
        sa.UniqueConstraint("building_name", name=op.f("uq_building_building_name")),
    )
    op.create_table(
        "employee",
        sa.Column("employee_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("employee_no", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("mobile", sa.String(length=64), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("employee_id", name=op.f("pk_employee")),
        sa.UniqueConstraint("employee_no", name="uq_employee_employee_no"),
    )
    op.create_index("ix_employee_mobile", "employee", ["mobile"], unique=False)
    op.create_index("ix_employee_name", "employee", ["name"], unique=False)
    op.create_table(
        "role",
        sa.Column("role_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("role_code", sa.String(length=50), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("role_id", name=op.f("pk_role")),
        sa.UniqueConstraint("role_code", name=op.f("uq_role_role_code")),
        sa.UniqueConstraint("role_name", name=op.f("uq_role_role_name")),
    )
    op.create_table(
        "supplier",
        sa.Column("supplier_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column("unified_social_credit_code", sa.String(length=50), nullable=True),
        sa.Column("bank_name", sa.String(length=200), nullable=True),
        sa.Column("bank_account", sa.String(length=255), nullable=True),
        sa.Column("registered_address", sa.String(length=500), nullable=True),
        sa.Column("contract_contact_info", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("supplier_id", name=op.f("pk_supplier")),
        sa.UniqueConstraint(
            "unified_social_credit_code", name="uq_supplier_unified_social_credit_code"
        ),
    )
    op.create_index("ix_supplier_supplier_name", "supplier", ["supplier_name"], unique=False)
    op.create_table(
        "employee_building",
        sa.Column("employee_id", sa.BigInteger(), nullable=False),
        sa.Column("building_id", sa.BigInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["building.building_id"],
            name=op.f("fk_employee_building_building_id_building"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_employee_building_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("employee_id", "building_id", name=op.f("pk_employee_building")),
    )
    op.create_index(
        "ix_employee_building_building_id", "employee_building", ["building_id"], unique=False
    )
    op.create_table(
        "employee_external_identity",
        sa.Column("identity_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_type", sa.String(length=30), nullable=False),
        sa.Column("platform_user_id", sa.String(length=150), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_employee_external_identity_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("identity_id", name=op.f("pk_employee_external_identity")),
        sa.UniqueConstraint(
            "platform_type", "platform_user_id", name="uq_employee_external_identity_platform_user"
        ),
    )
    op.create_index(
        "ix_employee_external_identity_employee_id",
        "employee_external_identity",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "employee_role",
        sa.Column("employee_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_employee_role_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.role_id"],
            name=op.f("fk_employee_role_role_id_role"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("employee_id", "role_id", name=op.f("pk_employee_role")),
    )
    op.create_index("ix_employee_role_role_id", "employee_role", ["role_id"], unique=False)
    op.create_table(
        "purchase_request",
        sa.Column("request_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_no", sa.String(length=40), nullable=False),
        sa.Column("building_id", sa.BigInteger(), nullable=False),
        sa.Column("applicant_employee_id", sa.BigInteger(), nullable=False),
        sa.Column("applicant_platform_type_snapshot", sa.String(length=30), nullable=False),
        sa.Column("applicant_platform_user_id_snapshot", sa.String(length=150), nullable=False),
        sa.Column("applicant_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("applicant_mobile_snapshot", sa.String(length=64), nullable=True),
        sa.Column("device_profession", sa.String(length=100), nullable=False),
        sa.Column("device_name", sa.String(length=200), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=150), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("application_reason", sa.Text(), nullable=False),
        sa.Column("applicant_remark", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_handler_employee_id", sa.BigInteger(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_request_quantity_positive")),
        sa.CheckConstraint("version >= 0", name=op.f("ck_purchase_request_version_non_negative")),
        sa.ForeignKeyConstraint(
            ["applicant_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_purchase_request_applicant_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["building.building_id"],
            name=op.f("fk_purchase_request_building_id_building"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_handler_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_purchase_request_current_handler_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("pk_purchase_request")),
        sa.UniqueConstraint("request_no", name=op.f("uq_purchase_request_request_no")),
    )
    op.create_index(
        "ix_purchase_request_applicant_employee_id",
        "purchase_request",
        ["applicant_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_request_building_id", "purchase_request", ["building_id"], unique=False
    )
    op.create_index(
        "ix_purchase_request_current_handler_employee_id",
        "purchase_request",
        ["current_handler_employee_id"],
        unique=False,
    )
    op.create_index("ix_purchase_request_status", "purchase_request", ["status"], unique=False)
    op.create_index(
        "ix_purchase_request_updated_at", "purchase_request", ["updated_at"], unique=False
    )
    op.create_table(
        "agent_conversation",
        sa.Column("conversation_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_type", sa.String(length=30), nullable=False),
        sa.Column("external_conversation_id", sa.String(length=150), nullable=True),
        sa.Column("purchase_request_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_agent_conversation_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"],
            ["purchase_request.request_id"],
            name=op.f("fk_agent_conversation_purchase_request_id_purchase_request"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("conversation_id", name=op.f("pk_agent_conversation")),
    )
    op.create_index(
        "ix_agent_conversation_employee_status",
        "agent_conversation",
        ["employee_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_agent_conversation_platform_conversation",
        "agent_conversation",
        ["platform_type", "external_conversation_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_conversation_purchase_request_id",
        "agent_conversation",
        ["purchase_request_id"],
        unique=False,
    )
    op.create_table(
        "notification_outbox",
        sa.Column("notification_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("receiver_employee_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_type", sa.String(length=30), nullable=False),
        sa.Column("receiver_platform_user_id_snapshot", sa.String(length=150), nullable=False),
        sa.Column("dedup_key", sa.String(length=100), nullable=False),
        sa.Column("payload", mysql.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["receiver_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_notification_outbox_receiver_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["purchase_request.request_id"],
            name=op.f("fk_notification_outbox_request_id_purchase_request"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("notification_id", name=op.f("pk_notification_outbox")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_notification_outbox_dedup_key")),
    )
    op.create_index(
        "ix_notification_outbox_event_type", "notification_outbox", ["event_type"], unique=False
    )
    op.create_index(
        "ix_notification_outbox_next_retry_at",
        "notification_outbox",
        ["next_retry_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_receiver_employee_id",
        "notification_outbox",
        ["receiver_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_request_id", "notification_outbox", ["request_id"], unique=False
    )
    op.create_index(
        "ix_notification_outbox_status", "notification_outbox", ["status"], unique=False
    )
    op.create_table(
        "purchase_execution",
        sa.Column("execution_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("purchaser_employee_id", sa.BigInteger(), nullable=False),
        sa.Column("purchaser_platform_type_snapshot", sa.String(length=30), nullable=False),
        sa.Column("purchaser_platform_user_id_snapshot", sa.String(length=150), nullable=False),
        sa.Column("purchaser_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("purchaser_mobile_snapshot", sa.String(length=64), nullable=True),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("supplier_tax_no_snapshot", sa.String(length=50), nullable=True),
        sa.Column("supplier_bank_name_snapshot", sa.String(length=200), nullable=True),
        sa.Column("supplier_bank_account_snapshot", sa.String(length=255), nullable=True),
        sa.Column("supplier_address_snapshot", sa.String(length=500), nullable=True),
        sa.Column("contract_contact_info_snapshot", sa.String(length=255), nullable=True),
        sa.Column("actual_unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("actual_total_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("purchased_at", sa.DateTime(), nullable=False),
        sa.Column("execution_remark", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "actual_total_price >= 0",
            name=op.f("ck_purchase_execution_actual_total_price_non_negative"),
        ),
        sa.CheckConstraint(
            "actual_unit_price >= 0",
            name=op.f("ck_purchase_execution_actual_unit_price_non_negative"),
        ),
        sa.CheckConstraint(
            "tax_rate IS NULL OR (tax_rate >= 0 AND tax_rate <= 100)",
            name=op.f("ck_purchase_execution_tax_rate_range"),
        ),
        sa.ForeignKeyConstraint(
            ["purchaser_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_purchase_execution_purchaser_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["purchase_request.request_id"],
            name=op.f("fk_purchase_execution_request_id_purchase_request"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.supplier_id"],
            name=op.f("fk_purchase_execution_supplier_id_supplier"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("execution_id", name=op.f("pk_purchase_execution")),
        sa.UniqueConstraint("request_id", name=op.f("uq_purchase_execution_request_id")),
    )
    op.create_index(
        "ix_purchase_execution_purchaser_employee_id",
        "purchase_execution",
        ["purchaser_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_execution_supplier_id", "purchase_execution", ["supplier_id"], unique=False
    )
    op.create_table(
        "purchase_operation_log",
        sa.Column("log_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("operator_employee_id", sa.BigInteger(), nullable=False),
        sa.Column("operator_platform_type_snapshot", sa.String(length=30), nullable=False),
        sa.Column("operator_platform_user_id_snapshot", sa.String(length=150), nullable=False),
        sa.Column("operator_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("operator_mobile_snapshot", sa.String(length=64), nullable=True),
        sa.Column("operator_role_id_snapshot", sa.BigInteger(), nullable=False),
        sa.Column("operator_role_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("assigned_to_employee_id", sa.BigInteger(), nullable=True),
        sa.Column("action_token", sa.String(length=64), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column("operation_summary", sa.Text(), nullable=True),
        sa.Column("operated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_purchase_operation_log_assigned_to_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operator_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_purchase_operation_log_operator_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["purchase_request.request_id"],
            name=op.f("fk_purchase_operation_log_request_id_purchase_request"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_purchase_operation_log")),
        sa.UniqueConstraint("action_token", name=op.f("uq_purchase_operation_log_action_token")),
    )
    op.create_index(
        "ix_purchase_operation_log_action_type",
        "purchase_operation_log",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_operation_log_assigned_to_employee_id",
        "purchase_operation_log",
        ["assigned_to_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_operation_log_operated_at",
        "purchase_operation_log",
        ["operated_at"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_operation_log_operator_employee_id",
        "purchase_operation_log",
        ["operator_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_operation_log_request_id",
        "purchase_operation_log",
        ["request_id"],
        unique=False,
    )
    op.create_table(
        "purchase_review",
        sa.Column("review_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("review_round", sa.Integer(), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("reviewer_employee_id", sa.BigInteger(), nullable=False),
        sa.Column("reviewer_platform_type_snapshot", sa.String(length=30), nullable=False),
        sa.Column("reviewer_platform_user_id_snapshot", sa.String(length=150), nullable=False),
        sa.Column("reviewer_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("reviewer_mobile_snapshot", sa.String(length=64), nullable=True),
        sa.Column("review_result", sa.String(length=20), nullable=True),
        sa.Column("review_opinion", sa.Text(), nullable=True),
        sa.Column("proposed_supplier_id", sa.BigInteger(), nullable=True),
        sa.Column("proposed_supplier_name", sa.String(length=200), nullable=True),
        sa.Column("supplier_contact_name", sa.String(length=100), nullable=True),
        sa.Column("supplier_contact_info", sa.String(length=255), nullable=True),
        sa.Column("supplier_link", sa.String(length=1000), nullable=True),
        sa.Column("estimated_unit_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("estimated_total_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("need_contract", sa.Boolean(), nullable=False),
        sa.Column("contract_type", sa.String(length=100), nullable=True),
        sa.Column("payment_method", sa.String(length=100), nullable=True),
        sa.Column("expected_arrival_date", sa.Date(), nullable=True),
        sa.Column("warranty_info", sa.String(length=255), nullable=True),
        sa.Column("review_remark", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "estimated_total_price IS NULL OR estimated_total_price >= 0",
            name=op.f("ck_purchase_review_estimated_total_price_non_negative"),
        ),
        sa.CheckConstraint(
            "estimated_unit_price IS NULL OR estimated_unit_price >= 0",
            name=op.f("ck_purchase_review_estimated_unit_price_non_negative"),
        ),
        sa.CheckConstraint(
            "review_round > 0", name=op.f("ck_purchase_review_review_round_positive")
        ),
        sa.ForeignKeyConstraint(
            ["proposed_supplier_id"],
            ["supplier.supplier_id"],
            name=op.f("fk_purchase_review_proposed_supplier_id_supplier"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["purchase_request.request_id"],
            name=op.f("fk_purchase_review_request_id_purchase_request"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_purchase_review_reviewer_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_purchase_review")),
        sa.UniqueConstraint("request_id", "review_round", name="uq_purchase_review_round"),
    )
    op.create_index(
        "ix_purchase_review_proposed_supplier_id",
        "purchase_review",
        ["proposed_supplier_id"],
        unique=False,
    )
    op.create_index(
        "ix_purchase_review_request_id", "purchase_review", ["request_id"], unique=False
    )
    op.create_index(
        "ix_purchase_review_reviewer_employee_id",
        "purchase_review",
        ["reviewer_employee_id"],
        unique=False,
    )
    op.create_table(
        "supplier_blacklist",
        sa.Column("blacklist_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("source_request_id", sa.BigInteger(), nullable=False),
        sa.Column("registrar_employee_id", sa.BigInteger(), nullable=False),
        sa.Column("registrar_platform_type_snapshot", sa.String(length=30), nullable=False),
        sa.Column("registrar_platform_user_id_snapshot", sa.String(length=150), nullable=False),
        sa.Column("registrar_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("registrar_mobile_snapshot", sa.String(length=64), nullable=True),
        sa.Column("blacklist_type", sa.String(length=50), nullable=False),
        sa.Column("blacklist_reason", sa.Text(), nullable=False),
        sa.Column("duration_type", sa.String(length=20), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.Column("released_by_employee_id", sa.BigInteger(), nullable=True),
        sa.Column("release_reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(duration_type = 'PERMANENT' AND end_at IS NULL) OR "
            "(duration_type = 'LIMITED' AND end_at IS NOT NULL)",
            name=op.f("ck_supplier_blacklist_duration_end_at_consistency"),
        ),
        sa.ForeignKeyConstraint(
            ["registrar_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_supplier_blacklist_registrar_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["released_by_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_supplier_blacklist_released_by_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_request_id"],
            ["purchase_request.request_id"],
            name=op.f("fk_supplier_blacklist_source_request_id_purchase_request"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.supplier_id"],
            name=op.f("fk_supplier_blacklist_supplier_id_supplier"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("blacklist_id", name=op.f("pk_supplier_blacklist")),
    )
    op.create_index(
        "ix_supplier_blacklist_registrar_employee_id",
        "supplier_blacklist",
        ["registrar_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_supplier_blacklist_released_by_employee_id",
        "supplier_blacklist",
        ["released_by_employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_supplier_blacklist_source_request_id",
        "supplier_blacklist",
        ["source_request_id"],
        unique=False,
    )
    op.create_index("ix_supplier_blacklist_status", "supplier_blacklist", ["status"], unique=False)
    op.create_index(
        "ix_supplier_blacklist_supplier_id", "supplier_blacklist", ["supplier_id"], unique=False
    )
    op.create_table(
        "warehouse_receipt",
        sa.Column("receipt_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_employee_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_platform_type_snapshot", sa.String(length=30), nullable=False),
        sa.Column("warehouse_platform_user_id_snapshot", sa.String(length=150), nullable=False),
        sa.Column("warehouse_name_snapshot", sa.String(length=100), nullable=False),
        sa.Column("warehouse_mobile_snapshot", sa.String(length=64), nullable=True),
        sa.Column("warehouse_location", sa.String(length=255), nullable=False),
        sa.Column("received_quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("receipt_remark", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "received_quantity > 0", name=op.f("ck_warehouse_receipt_received_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["purchase_request.request_id"],
            name=op.f("fk_warehouse_receipt_request_id_purchase_request"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_employee_id"],
            ["employee.employee_id"],
            name=op.f("fk_warehouse_receipt_warehouse_employee_id_employee"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("receipt_id", name=op.f("pk_warehouse_receipt")),
        sa.UniqueConstraint("request_id", name=op.f("uq_warehouse_receipt_request_id")),
    )
    op.create_index(
        "ix_warehouse_receipt_warehouse_employee_id",
        "warehouse_receipt",
        ["warehouse_employee_id"],
        unique=False,
    )
    op.create_table(
        "agent_message",
        sa.Column("message_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column("external_message_id", sa.String(length=150), nullable=True),
        sa.Column("sender_type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversation.conversation_id"],
            name=op.f("fk_agent_message_conversation_id_agent_conversation"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_agent_message")),
        sa.UniqueConstraint(
            "conversation_id",
            "external_message_id",
            name="uq_agent_message_conversation_external_message",
        ),
    )
    op.create_index(
        "ix_agent_message_conversation_created",
        "agent_message",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_session_state",
        sa.Column("state_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column("current_action", sa.String(length=30), nullable=False),
        sa.Column("state_data", mysql.JSON(), nullable=True),
        sa.Column("missing_fields", mysql.JSON(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("saved_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversation.conversation_id"],
            name=op.f("fk_agent_session_state_conversation_id_agent_conversation"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("state_id", name=op.f("pk_agent_session_state")),
        sa.UniqueConstraint("conversation_id", name=op.f("uq_agent_session_state_conversation_id")),
    )

    role_seed_table = sa.table(
        "role",
        sa.column("role_id", sa.BigInteger()),
        sa.column("role_code", sa.String()),
        sa.column("role_name", sa.String()),
        sa.column("description", sa.String()),
        sa.column("status", sa.Boolean()),
    )
    op.bulk_insert(
        role_seed_table,
        [
            {
                "role_id": 1,
                "role_code": "APPLICANT",
                "role_name": "需求人",
                "description": "发起采购申请",
                "status": True,
            },
            {
                "role_id": 2,
                "role_code": "BUILDING_MANAGER",
                "role_name": "楼长",
                "description": "审核并处理所管理楼宇的采购申请",
                "status": True,
            },
            {
                "role_id": 3,
                "role_code": "PURCHASER",
                "role_name": "采购员",
                "description": "完成采购执行和签约信息填写",
                "status": True,
            },
            {
                "role_id": 4,
                "role_code": "WAREHOUSE_MANAGER",
                "role_name": "仓库管理员",
                "description": "完成仓库位置、入库数量和备注填写",
                "status": True,
            },
            {
                "role_id": 5,
                "role_code": "ADMIN",
                "role_name": "系统管理员",
                "description": "维护基础数据和同步配置",
                "status": True,
            },
        ],
    )

    building_seed_table = sa.table(
        "building",
        sa.column("building_id", sa.BigInteger()),
        sa.column("building_name", sa.String()),
        sa.column("status", sa.Boolean()),
    )
    op.bulk_insert(
        building_seed_table,
        [
            {"building_id": 1, "building_name": "一号楼", "status": True},
            {"building_id": 2, "building_name": "二号楼", "status": True},
            {"building_id": 3, "building_name": "三号楼", "status": True},
            {"building_id": 4, "building_name": "四号楼", "status": True},
            {"building_id": 5, "building_name": "五号楼", "status": True},
            {"building_id": 6, "building_name": "六号楼", "status": True},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL automatically removes a table's indexes. Dropping indexes first can
    # fail when an index is still required by a foreign-key constraint.
    # ``if_exists`` also lets an interrupted non-transactional MySQL downgrade
    # resume safely.
    op.drop_table("agent_session_state", if_exists=True)
    op.drop_table("agent_message", if_exists=True)
    op.drop_table("warehouse_receipt", if_exists=True)
    op.drop_table("supplier_blacklist", if_exists=True)
    op.drop_table("purchase_review", if_exists=True)
    op.drop_table("purchase_operation_log", if_exists=True)
    op.drop_table("purchase_execution", if_exists=True)
    op.drop_table("notification_outbox", if_exists=True)
    op.drop_table("agent_conversation", if_exists=True)
    op.drop_table("purchase_request", if_exists=True)
    op.drop_table("employee_role", if_exists=True)
    op.drop_table("employee_external_identity", if_exists=True)
    op.drop_table("employee_building", if_exists=True)
    op.drop_table("supplier", if_exists=True)
    op.drop_table("role", if_exists=True)
    op.drop_table("employee", if_exists=True)
    op.drop_table("building", if_exists=True)
