"""allow incomplete purchase request drafts

Revision ID: 816575c8be0c
Revises: 2630b41e0575
Create Date: 2026-07-29 16:56:10.417443
"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "816575c8be0c"
down_revision: str | Sequence[str] | None = "2630b41e0575"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "purchase_request",
        "device_profession",
        existing_type=mysql.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "purchase_request", "device_name", existing_type=mysql.VARCHAR(length=200), nullable=True
    )
    op.alter_column(
        "purchase_request",
        "quantity",
        existing_type=mysql.DECIMAL(precision=18, scale=3),
        nullable=True,
    )
    op.alter_column(
        "purchase_request", "unit", existing_type=mysql.VARCHAR(length=30), nullable=True
    )
    op.alter_column(
        "purchase_request", "application_reason", existing_type=mysql.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Older schema cannot represent incomplete drafts. Use explicit placeholders
    # so a rollback remains executable without deleting draft rows.
    op.execute(
        """
        UPDATE purchase_request
        SET device_profession = COALESCE(device_profession, ''),
            device_name = COALESCE(device_name, ''),
            quantity = COALESCE(quantity, 1.000),
            unit = COALESCE(unit, ''),
            application_reason = COALESCE(application_reason, '')
        WHERE device_profession IS NULL
           OR device_name IS NULL
           OR quantity IS NULL
           OR unit IS NULL
           OR application_reason IS NULL
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "purchase_request", "application_reason", existing_type=mysql.TEXT(), nullable=False
    )
    op.alter_column(
        "purchase_request", "unit", existing_type=mysql.VARCHAR(length=30), nullable=False
    )
    op.alter_column(
        "purchase_request",
        "quantity",
        existing_type=mysql.DECIMAL(precision=18, scale=3),
        nullable=False,
    )
    op.alter_column(
        "purchase_request", "device_name", existing_type=mysql.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "purchase_request",
        "device_profession",
        existing_type=mysql.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###
